### ISSUE TITLE
Mobile app docs request

### ISSUE THREAD

**Issue by galaris** [krakenrf/krakensdr_docs#10]
Please add some explanation on the settings of the mobile app.

**Comment by krakenrf** [comment]
Hi, most of the settings are described in the Wiki https://github.com/krakenrf/krakensdr_docs/wiki/06.-Android-App-Guide

Is there anything specific missing that you'd like?

**Comment by galaris** [comment]
Wow, I've actually missed that page, thank you. Another topic, sometimes my app gets really slow (mainly when I use the plot feature), and even crashes on me (I have a Pixel 4a 5g with a custom rom). There has been numerous times where my signal hunting attempt has been canceled due to a crash. 

Is there a way to get application debug logs so I can send the crash details to you? I suspect that it has to do with the custom rom, but I've never experienced this much crashing with my other apps :(

**Comment by krakenrf** [comment]
Are you running "Plot Log File" checked when using it? That could get a bit sluggish when the log grows too large as this does a complete recalculation from scratch when a new data point comes in. I've seen some people running that feature during live operation, but really it's intended for post drive offline analysis only especially as it clutters the map up.

Only the heatmap grid should be used during live driving. That is efficient as it only needs to update one data point at a time instead of a full recalculation. I'll try to make that more clear in the app and docs, and see if the plotting line feature can be optimized for live driving in the future too.

I've actually not seen the app crash on any device recently, but I've not been running with plot log file enabled. Can you send the recording of the data CSV logfiles to thekraken@krakenrf.com, or upload them here if you're comfortable publicly sharing the location data in your logfiles? I can try to simulate your drive and see where it crashes.

**Comment by galaris** [comment]
Hopefully I can get some time to play more with the Kraken soon, I will report to that email address if the application still keeps crashing after following your advice.
